### ISSUE TITLE
Restructure the project

### ISSUE THREAD

**Issue by JudgeZarbi** [JudgeZarbi/smb2-team-transfer-tool#2]
This issue will be where the rest of the issues point to, and give a space to put down my thoughts.

At present, I have two thoughts for structuring the project.

```
root
├── main.py
├── teams
│   ├── import.py
│   └── export.py
├── logos
│   ├── import.py
│   └── export.py
└── ...
```

```
root
├── main.py
├── export
│   ├── teams.py
│   ├── logos.py
│   └── ...
├── import
│   ├── teams.py
│   ├── logos.py
│   └── ...
└── ...
```

Preferring the second one right now, but I'll leave the thought open.

- [x] #3 - Move the JSON processors to their own file
- [x] #4 - Move the export code to its own file
- [x] #7 - Move the import code to its own file
- [x] #8 - Separate the save handling code
- [x] #14 - Move the connection code to a utility file

**Comment by JudgeZarbi** [comment]
This is the key issue that will cover most of milestone v0.2.

**Comment by JudgeZarbi** [comment]
I've decided that the second structure is what I'll go with.
